### ISSUE TITLE
bld doesn't resolve pom import dependencies

### ISSUE THREAD

**Issue by ethauvin** [rife2/rife2#30]
For example, in this [sample project](https://github.com/ethauvin/bld-tester):

The dependencies for the bitly-shorten  library resolve as:

```shell
compile:
└─ net.thauvin.erik:bitly-shorten:0.9.4-SNAPSHOT
   └─ org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.20
      ├─ org.jetbrains.kotlin:kotlin-stdlib:1.8.20
      │  ├─ org.jetbrains.kotlin:kotlin-stdlib-common:1.8.20
      │  └─ org.jetbrains:annotations:13.0
      └─ org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.20

runtime:
└─ net.thauvin.erik:bitly-shorten:0.9.4-SNAPSHOT
   ├─ com.squareup.okhttp3:okhttp:4.10.0
   ├─ com.squareup.okhttp3:logging-interceptor:4.10.0
   └─ org.json:json:20230227
```

Under Gradle the dependencies resolve as:

```shell
+--- net.thauvin.erik:bitly-shorten:0.9.4-SNAPSHOT
|    +--- org.jetbrains.kotlin:kotlin-bom:1.8.0
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.8.0 -> 1.8.20 (c)
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0 -> 1.8.20 (c)
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0 -> 1.8.20 (c)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.8.0 -> 1.8.20 (c)
|    +--- com.squareup.okhttp3:okhttp:4.10.0
|    |    +--- com.squareup.okio:okio:3.0.0
|    |    |    \--- com.squareup.okio:okio-jvm:3.0.0
|    |    |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31 -> 1.8.20 (*)
|    |    |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31 -> 1.8.20
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.6.20 -> 1.8.20 (*)
|    +--- com.squareup.okhttp3:logging-interceptor:4.10.0
|    |    +--- com.squareup.okhttp3:okhttp:4.10.0 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10 -> 1.8.20 (*)
|    +--- org.json:json:20220924 -> 20230227
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0 -> 1.8.20 (*)
````

The [sample project](https://github.com/ethauvin/bld-tester) will not run under bld.

**Comment by gbevin** [comment]
In this case, this needs to be supported by `bld`:

```
<dependency>
<groupId>org.jetbrains.kotlin</groupId>
<artifactId>kotlin-bom</artifactId>
<version>1.8.20</version>
<type>pom</type>
<scope>import</scope>
</dependency>
```

**Comment by gbevin** [comment]
What is the error you get when you run this?

**Comment by gbevin** [comment]
Nevermind, found the project you linked

```
./bld run
Exception in thread "main" java.lang.NoClassDefFoundError: okio/Buffer
	at okhttp3.ResponseBody$Companion.create(ResponseBody.kt:248)
	at okhttp3.ResponseBody$Companion.create$default(ResponseBody.kt:247)
	at okhttp3.internal.Util.<clinit>(Util.kt:65)
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1239)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
	at net.thauvin.erik.bitly.Utils.call(Utils.kt:78)
	at net.thauvin.erik.bitly.Utils.call$default(Utils.kt:69)
	at net.thauvin.erik.bitly.Bitlinks.shorten(Bitlinks.kt:238)
	at net.thauvin.erik.bitly.Bitlinks.shorten$default(Bitlinks.kt:221)
	at net.thauvin.erik.bitly.Bitlinks.shorten(Bitlinks.kt)
	at net.thauvin.erik.BldTesterMain.getMessage(BldTesterMain.java:11)
	at net.thauvin.erik.BldTesterMain.main(BldTesterMain.java:7)
Caused by: java.lang.ClassNotFoundException: okio.Buffer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 12 more
```
